### ISSUE TITLE
Please help (Urgent)

### ISSUE THREAD

**Issue by Alex0084** [Travelport/travelport-uapi-tutorial-php#99]
Hello,

We have this error we need help with it please.

<?xml version="1.0" encoding="UTF-8"?>
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <soapenv:Body>
    <soapenv:Fault>
      <faultcode>soapenv:Server.userException</faultcode>
      <faultstring>Uncaught Service Exception cause:com.cendant.tds.soa.framework.ServiceException: XTS Translation of Data Failed when converting the SingleXML request into a Host Format.</faultstring>
      <detail>
        <ns1:stackTrace xmlns:ns1="http://xml.apache.org/axis/">

********* UnKnown Service Exception ************
Occured: 10/16/2017 11:14:54 AM
Originator address: VHLPNWSAS011 (10.7.93.21)
Service domain: wsSTP
Service name: XMLSelect

********* Details below ********

com.cendant.tds.soa.framework.ServiceException: XTS Translation of Data Failed when converting the SingleXML request into a Host Format.
	at com.cendant.tds.services.xws.galileo.xts.XtsTransaction.translateSingleXmltoSD(XtsTransaction.java:84)
	at com.cendant.tds.services.xws.galileo.xws.host.transaction.XwsHostSubmitXmlOnSession.processXMLSelectTransaction(XwsHostSubmitXmlOnSession.java:45)
	at com.cendant.tds.services.xws.processing.HASTransactionManager.processHASTransaction(HASTransactionManager.java:82)
	at com.cendant.tds.services.xws.service.XmlSelectService.processRequest(XmlSelectService.java:175)
	at com.cendant.tds.soa.framework.container.CompartmentBase.processRequestInternal(CompartmentBase.java:613)
	at com.cendant.tds.soa.framework.container.CompartmentBase.processRequest(CompartmentBase.java:446)
	at com.cendant.tds.soa.framework.container.ContainerImpl.processRequest(ContainerImpl.java:630)
	at com.cendant.tds.soa.framework.adapter.LocalAdapter.sendRequest(LocalAdapter.java:45)
	at com.cendant.tds.soa.framework.bus.BusImpl.callService(BusImpl.java:65)
	at com.cendant.tds.soa.framework.broker.BrokerImpl.processRequestInternal(BrokerImpl.java:381)
	at com.cendant.tds.soa.framework.broker.BrokerImpl.processRequestBothPaths(BrokerImpl.java:183)
	at com.cendant.tds.soa.framework.broker.BrokerImpl.processRequest(BrokerImpl.java:146)
	at com.cendant.tds.soa.framework.proxies.SOAGatewayProxy.processRequestInternal(SOAGatewayProxy.java:126)
	at com.cendant.tds.soa.framework.proxies.SOAGatewayProxy.processRequest(SOAGatewayProxy.java:79)
	at sun.reflect.GeneratedMethodAccessor76.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.axis.providers.java.MsgProvider.processMessage(MsgProvider.java:162)
	at org.apache.axis.providers.java.JavaProvider.invoke(JavaProvider.java:333)
	at org.apache.axis.strategies.InvocationStrategy.visit(InvocationStrategy.java:71)
	at org.apache.axis.SimpleChain.doVisiting(SimpleChain.java:150)
	at org.apache.axis.SimpleChain.invoke(SimpleChain.java:120)
	at org.apache.axis.handlers.soap.SOAPService.invoke(SOAPService.java:481)
	at org.apache.axis.server.AxisServer.invoke(AxisServer.java:323)
	at org.apache.axis.transport.http.AxisServlet.doPost(AxisServlet.java:854)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:641)
	at org.apache.axis.transport.http.AxisServletBase.service(AxisServletBase.java:339)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:722)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
	at com.cendant.tds.soa.framework.gateway.filter.CompressionFilter.doFilter(CompressionFilter.java:70)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
	at com.cendant.tds.soa.framework.gateway.filter.WSDLFilter.doFilter(WSDLFilter.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
	at com.cendant.tds.soa.framework.gateway.filter.ExpansionFilter.doFilter(ExpansionFilter.java:76)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:224)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:169)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:168)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:98)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:927)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:407)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:987)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:579)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:307)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

</ns1:stackTrace>
      </detail>
    </soapenv:Fault>
  </soapenv:Body>
</soapenv:Envelope>

**Comment by vivekjyotipramanik** [comment]
Hi Alex0084,

Looks like you are using XMlSelect. We do not support XMLSelect through github UAPI. Please create an ORS Ticket or MyTravelport ticket and the API Support team will assist you regarding this. Thanks.

**Comment by Alex0084** [comment]
We are tying to use Using Universal API and Legacy API Products Together

Sir can just tell us the best and fastest way of connecting the UAPI via GWS credentials please.

Thank you for your support

**Comment by Alex0084** [comment]
OR any other way to connect HAP logins into the UAPI please ?

**Comment by vivekjyotipramanik** [comment]
Hi  Alex0084,

UAPI can not be connected using GWS credentials, UAPI needs to be run using UAPI credentials. Could you please create an ORS ticket or MyTravelport ticket as you are using GWS. An API Analyst will assist you regarding this. Thanks.
